[package]
name = "rust_renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
png = "0.17.13"
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0", features = ["derive", "rc"] }
typetag = "0.2"
serde_json = "1.0"
